In [ ]:
# Import library
import numpy as np

from numpy import pi

In [ ]:
a =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

In [ ]:
a.shape

(150, 4)

In [ ]:
#!pip install numpy==1.24

In [ ]:
np.__version__

'1.21.6'

### Creating

In [ ]:
# Create a 1d array from a list
list1 = [0, 1, 2, 3, 4]
arr1d = np.array(list1)
# arr1d = np.array([0, 1, 2, 3, 4])
print(type(arr1d))
print(arr1d.shape)
arr1d

<class 'numpy.ndarray'>
(5,)


array([0, 1, 2, 3, 4])

In [ ]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [ ]:
np.array([1, 2, 3, 4, 5], ndmin = 1)

array([1, 2, 3, 4, 5])

In [ ]:
# Create a 2d array from a list of lists
list2 = [[0, 1., 2], [3, 4, 5], [6, 7, 8]]
arr2d = np.array(list2)

# shape
print('Shape: ', arr2d.shape)
# dtype
print('Datatype: ', arr2d.dtype)
# size
print('Size: ', arr2d.size)
# ndim
print('Num Dimensions: ', arr2d.ndim)

arr2d

Shape:  (3, 3)
Datatype:  float64
Size:  9
Num Dimensions:  2


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3, 4), dtype=np.float16)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)

In [ ]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(10, 30, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
x = np.linspace(0, 2*pi, 8)
f = np.sin(x)

In [ ]:
f

array([ 0.00000000e+00,  7.81831482e-01,  9.74927912e-01,  4.33883739e-01,
       -4.33883739e-01, -9.74927912e-01, -7.81831482e-01, -2.44929360e-16])

In [ ]:
np.set_printoptions(precision=2)
np.logspace(start=1, stop=50, num=10, base=2.71)

array([2.71e+00, 6.17e+02, 1.40e+05, 3.20e+07, 7.28e+09, 1.66e+12,
       3.77e+14, 8.59e+16, 1.96e+19, 4.45e+21])

In [ ]:
a = [[1,2,3],[4,5,6]]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

Tile:    [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
Repeat:  [1 1 2 2 3 3 4 4 5 5 6 6]


### Set types

In [ ]:
# Create a float 2d array
arr2d_f = np.array(list2, dtype='float') # 'float', 'int', 'bool', 'str', 'object', 'complex'
                                         # 'float32', 'float64', 'int8', 'int16', 'int32', 'int64'
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
# Convert to 'int' datatype
arr2d_i = arr2d_f.astype('str')
arr2d_i

array([['0.0', '1.0', '2.0'],
       ['3.0', '4.0', '5.0'],
       ['6.0', '7.0', '8.0']], dtype='<U32')

In [ ]:
# Convert to int then to str datatype
arr2d_s = arr2d_f.astype('int').astype('str')
arr2d_s

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

In [ ]:
# Create a boolean array
arr2d_b = np.array([-1, 0, 10], dtype='bool')
arr2d_b

array([ True, False,  True])

In [ ]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [ ]:
# Convert an array back to a list
arr1d_obj.tolist()

[1, 'a']

In [ ]:
bool(np.nan)

True

### Random numbers

In [ ]:
np.random.seed(100)

# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# One random number between [0,1)
print(np.random.random())

# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.1, .3, 0.1, 0.4, 0.1]))

[[0.54 0.28]
 [0.42 0.84]]
[[ 0.98  0.51]
 [ 0.22 -1.07]]
[[4 0]
 [9 6]]
0.3074232114748938
[[0.95 0.13]
 [0.08 0.31]]
['u' 'o' 'o' 'o' 'e' 'e' 'o' 'a' 'i' 'e']
['o' 'e' 'o' 'i' 'e' 'i' 'i' 'i' 'a' 'o']


### Concatenate

In [ ]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Vertical Stack Equivalents (Row wise)
np.concatenate([a, b], axis=0)
np.vstack([a,b])
np.r_[a,b]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Horizontal Stack Equivalents (Coliumn wise)
np.concatenate([a, b], axis=1)
np.hstack([a,b])
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
np.r_[[1, 2, 3], 0, 0, [4, 5, 6]]

array([1, 2, 3, 0, 0, 4, 5, 6])

### Flatten

In [ ]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [ ]:
arr2.flatten()

array([1., 2., 3., 4., 3., 4., 5., 6., 5., 6., 7., 8.])

In [ ]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [ ]:
b1 = arr2.flatten()
b1[0] = 100  # changing b1 does not affect arr2
arr2
#b1

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [ ]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()
b2[0] = 101  # changing b2 changes arr2 also
arr2

array([[101.,   2.,   3.,   4.],
       [  3.,   4.,   5.,   6.],
       [  5.,   6.,   7.,   8.]])

### Reshape

In [ ]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(2, 6)

array([[101.,   2.,   3.,   4.,   3.,   4.],
       [  5.,   6.,   5.,   6.,   7.,   8.]])

### Missing values

In [ ]:
# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

array([[101.,   2.,   3.,   4.],
       [  3.,  nan,  inf,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
np.isnan(arr2) | np.isinf(arr2)

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [ ]:
# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
missing_bool
arr2[missing_bool] = -1
arr2

array([[101.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
missing_bool

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

### Unique

In [ ]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [ ]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]


### Indexing

In [ ]:
arr2

array([[101.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
arr2[:2, :2]

array([[101.,   2.],
       [  3.,  -1.]])

In [ ]:
arr2[1:3, 0:3]

array([[ 3., -1., -1.],
       [ 5.,  6.,  7.]])

In [ ]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]
arr2a[:2, :2] = 100  # 100 will reflect in arr2
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101  # 101 will not reflect in arr2
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
# add new dimension
arr3d = arr2[:, np.newaxis , : ]
arr3d

array([[[100., 100.,   3.,   4.]],

       [[100., 100.,  -1.,   6.]],

       [[  5.,   6.,   7.,   8.]]])

In [ ]:
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
b = arr2 > 4
b

array([[ True,  True, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
arr2[b]

array([100., 100., 100., 100.,   6.,   5.,   6.,   7.,   8.])

In [ ]:
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array: ", arr_rand)

# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)

Array:  [8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4]),)


In [ ]:
# Take items at given index
arr_rand.take(index_gt5)

array([[8, 8, 7, 7]])

In [ ]:
# If value > 5, then yield 'gt5' else 'le5'
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

In [ ]:
# Location of the max
print('Position of max value: ', np.argmax(arr_rand))

# Location of the min
print('Position of min value: ', np.argmin(arr_rand))

Position of max value:  0
Position of min value:  5


### Reversing

In [ ]:
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
# Reverse only the row positions
arr2[::-1, ]

array([[  5.,   6.,   7.,   8.],
       [100., 100.,  -1.,   6.],
       [100., 100.,   3.,   4.]])

In [ ]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[  8.,   7.,   6.,   5.],
       [  6.,  -1., 100., 100.],
       [  4.,   3., 100., 100.]])

### Iteration

In [ ]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)

print(a)
print('\n')

for x in np.nditer(a):
    print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


0
5
10
15
20
25
30
35
40
45
50
55


### Sorting

In [ ]:
np.random.seed(100)
arr = np.random.randint(1,6, size=[8, 4])
arr

array([[1, 1, 4, 1],
       [3, 5, 3, 3],
       [3, 3, 2, 1],
       [1, 5, 4, 5],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [2, 4, 5, 5],
       [4, 4, 4, 2]])

In [ ]:
# Sort each columns of arr
np.sort(arr, axis=1)

array([[1, 1, 1, 4],
       [3, 3, 3, 5],
       [1, 2, 3, 3],
       [1, 4, 5, 5],
       [1, 2, 3, 4],
       [3, 4, 5, 5],
       [2, 4, 5, 5],
       [2, 4, 4, 4]])

In [ ]:
# Get the index positions that would sort the array
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]


In [ ]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [ ]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[1, 1, 4, 1],
       [1, 5, 4, 5],
       [2, 4, 5, 5],
       [3, 5, 3, 3],
       [3, 3, 2, 1],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [4, 4, 4, 2]])

In [ ]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[4, 4, 4, 2],
       [3, 4, 5, 5],
       [3, 1, 4, 2],
       [3, 3, 2, 1],
       [3, 5, 3, 3],
       [2, 4, 5, 5],
       [1, 5, 4, 5],
       [1, 1, 4, 1]])

In [ ]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0]))
arr[lexsorted_index]

array([[1, 1, 4, 1],
       [1, 5, 4, 5],
       [2, 4, 5, 5],
       [3, 1, 4, 2],
       [3, 3, 2, 1],
       [3, 4, 5, 5],
       [3, 5, 3, 3],
       [4, 4, 4, 2]])

### mean, min, max

In [ ]:
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  36.5
Max value is:  100.0
Min value is:  -1.0


In [ ]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

Column wise minimum:  [ 5.  6. -1.  4.]
Row wise minimum:  [ 3. -1.  5.]


In [ ]:
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
# Cumulative Sum
np.cumsum(arr2)

array([100., 200., 203., 207., 307., 407., 406., 412., 417., 423., 430.,
       438.])

### Applying functions

In [ ]:
# Define a scalar function
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

# On a scalar
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))

# On a vector, doesn't work
#print('x = [10, 11, 12] returns ', foo([10, 11, 12]))  # Error

x = 10 returns  5.0
x = 11 returns  121


In [ ]:
# Vectorize foo(). Make it work on vectors.
foo_v = np.vectorize(foo, otypes=[float])

print('x = [10, 11, 12] returns ', foo_v([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] returns ', foo_v([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returns  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returns  [[  5. 121.   6.]
 [  1.   1.   9.]]


In [ ]:
# Create a 4x10 random array
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [ ]:
# Define func1d
def max_minus_min(x):
    return np.max(x) - np.min(x)

# Apply along the rows
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# Apply along the columns
print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Row wise:  [8 8 6 8]
Column wise:  [7 8 2 7 6 5 8 5 5 5]


In [ ]:
def max_minus_min_fast(x, axis):
    return x.max(axis=axis) - x.min(axis=axis)

In [ ]:
# Apply along the rows
print('Row wise: ', max_minus_min_fast(arr_x, 1))

# Apply along the columns
print('Column wise: ', max_minus_min_fast(arr_x, 0))

Row wise:  [8 8 6 8]
Column wise:  [7 8 2 7 6 5 8 5 5 5]


In [ ]:
%timeit np.apply_along_axis(max_minus_min, 1, arr=arr_x)

116 µs ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit max_minus_min_fast(arr_x, 1)

5.49 µs ± 141 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Linear algebra

In [ ]:
arr2

array([[100., 100.,   3.,   4.],
       [100., 100.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [ ]:
arr2.transpose()

array([[100., 100.,   5.],
       [100., 100.,   6.],
       [  3.,  -1.,   7.],
       [  4.,   6.,   8.]])

In [ ]:
arr_tmp = np.array(np.random.randn(4, 3)*10, dtype=np.int64)
arr_tmp

array([[ -4,   0,   2],
       [ 14,   5, -23],
       [ 13, -11,   0],
       [  1,   5,  11]])

In [ ]:
np.dot(arr2, arr_tmp)

array([[ 1043.,   487., -2056.],
       [  993.,   541., -2034.],
       [  163.,    -7.,   -40.]])

In [ ]:
np.linalg.matrix_power(arr2[:, :3], 2)

array([[20015., 20018.,   221.],
       [19995., 19994.,   193.],
       [ 1135.,  1142.,    58.]])

In [ ]:
np.linalg.det(arr2[:, :3])

400.0000000000002

In [ ]:
np.linalg.eig(arr2[:, :3])

(array([200.06,   0.3 ,   6.64]),
 array([[-0.71, -0.7 ,  0.27],
        [-0.71,  0.7 , -0.28],
        [-0.04, -0.11,  0.92]]))